<a href="https://colab.research.google.com/github/eshikaa11/Foundation-AI/blob/main/num.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [9]:
a =np.array([1,2,3,5,7,12])

In [10]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,100,11) # creates arrays with evenly spaced numbers within a spaced elements in a given range

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multidimensional arrays

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [17]:
n[2] = [1,1,1]
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [18]:
n[:, 2] = [0, 1, 2]
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

# Randomly generated arrays


In [19]:
np.random.rand(3)

array([0.25792823, 0.03883434, 0.28664877])

In [21]:
np.random.seed(2)
np.random.randn(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

# Element-wise You can perform operations on entire arrays elemet by element

In [27]:
# a = np.arange()
# a

TypeError: 'int' object is not callable

In [23]:
b = (10 +(a * 2))
b

20

# Comparison operations
You can perform element-wise

In [28]:
a >= 2


True

In [26]:
a > b

False